//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Lurker.UI
{
    using System.Windows;
    using System.Windows.Controls;

    /// <summary>
    /// Represents the icon pack data.
    /// </summary>
    public static class IconPackData
    {
	    #region Properties

        /// <summary>
        /// Gets the icon pack data for the icon InInstance.
        /// </summary>
        public static string InInstance => "M149.996,0C67.157,0,0.001,67.158,0.001,149.997c0,82.837,67.156,150,149.995,150s150-67.163,150-150   C299.996,67.156,232.835,0,149.996,0z M150.453,220.763v-0.002h-0.916H85.465c0-46.856,41.152-46.845,50.284-59.097l1.045-5.587   c-12.83-6.502-21.887-22.178-21.887-40.512c0-24.154,15.712-43.738,35.089-43.738c19.377,0,35.089,19.584,35.089,43.738   c0,18.178-8.896,33.756-21.555,40.361l1.19,6.349c10.019,11.658,49.802,12.418,49.802,58.488H150.453z";

	    #endregion
    }

    /// <summary>
    /// Represents the icon pack control.
    /// </summary>
    public class IconPack : Control
    {
        #region Fields

        /// <summary>
        /// The data property that contains the icon pack data.
        /// </summary>
        public static readonly DependencyProperty DataProperty =
            DependencyProperty.Register(nameof(Data), typeof(string), typeof(IconPack));

        #endregion

        #region Constructors

		/// <summary>
        /// Initializes the <see cref="IconPack"/> class.
        /// </summary>
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1810:InitializeReferenceTypeStaticFieldsInline", Justification = "Reviewed.")]
        static IconPack()
        {
            DefaultStyleKeyProperty.OverrideMetadata(typeof(IconPack), new FrameworkPropertyMetadata(typeof(IconPack)));
        }

        #endregion

        #region Properties

		/// <summary>
        /// Gets or sets the icon pack data.
        /// </summary>
        public string Data
        {
            get
            {
                return this.GetValue(DataProperty).ToString();
            }

            set
            {
                this.SetValue(DataProperty, value);
            }
        }

        #endregion
    }
}
